### ISSUE TITLE
test example doesn't work

### ISSUE THREAD

**Issue by gerchicov-bp** [DenHeadless/ZoomInteractiveTransition#14]
[!] Error installing PlaceKit
[!] /opt/local/bin/git clone git@github.com:larsacus/PlaceKit.git /var/folders/sy/4_wxmzmj75j733p9k30rms7d7rjblp/T/d20160115-46461-ebtspu --single-branch --depth 1 --branch 1.1.0

Cloning into '/var/folders/sy/4_wxmzmj75j733p9k30rms7d7rjblp/T/d20160115-46461-ebtspu'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by DenHeadless** [comment]
I believe you have the issue with git or cocoapods. PlaceKit is a public Github repo, that should be cloned without ssh key.

I've checked pod try ZoomInteractiveTransition command, and pod install from local clone - everything works.

**Comment by gerchicov-bp** [comment]
You are perfect. The issue still exists but you close it.
I cloned your repo with sourcetree, went into example folder and ran ```pod install```... The same issue. And I have the same issue with ```pod try```
I downloaded a lot of repositories yesterday - only your PlaceKit gives this issue (or your project causes it if it is configured incorrectly).

**Comment by DenHeadless** [comment]
First of all, PlaceKit is not mine, it's just a placeholder framework, that was convenient for example project. Second - I've tried on two machines, and several contributors tried it as well - everything works. So it must be something on your machine that causing this issue.

And i closed the issue, because there's nothing i can proceed with, how do you suggest i debug the issue i can't even see? 

Try updating CocoaPods version, maybe updating git. Try running

```
pod install --verbose
```

and 

```
pod try ZoomInteractiveTransition --verbose
```

And by the way, try

```
pod try PlaceKit
``

Thats all I can suggest.

**Comment by gerchicov-bp** [comment]
No, the same issue.
I could suggest you an "extreme" solution - you could fork PlaceKit and link your project with this copy with proper settings. So even if the main repository has such troubles then your one will work anyways

**Comment by DenHeadless** [comment]
Okay, so i have an idea, what's happening here. PlaceKit uses SSH url for it's CocoaPod:

https://github.com/larsacus/PlaceKit/blob/master/PlaceKit.podspec#L10

Which means you need an SSH key configured on your machine to be able to clone it via pod install or pod try. 

You can generate SSH key for Github and try again - https://help.github.com/articles/generating-ssh-keys/

**Comment by gerchicov-bp** [comment]
Yes, now it works. You should add this instruction into your readme file
