### ISSUE TITLE
Images which start off underneath the navigation bar will appear above the navigation bar before animating into place

### ISSUE THREAD

**Issue by mattdna** [DenHeadless/ZoomInteractiveTransition#16]
My app has a table view of images which can be scrolled partially off screen.  When tapping on an image  to navigate to another view controller, the image suddenly appears above the navigation bar before animating into its new position and size.
Is there a way to ensure that the animated image remains underneath the navigation bar?  I've tried calling [containerView bringSubviewToFront:navigationBar] just before commencing the animation, but this doesn't seem to make any difference.

**Comment by DenHeadless** [comment]
Sorry, have no idea :( This really depends on your views setup. I would suggest looking into those lines, that specifically determine where animating view should be before and after transition

https://github.com/DenHeadless/ZoomInteractiveTransition/blob/master/ZoomTransition/ZoomInteractiveTransition.m#L119
https://github.com/DenHeadless/ZoomInteractiveTransition/blob/master/ZoomTransition/ZoomInteractiveTransition.m#L154

Maybe frame is not correct or something like that.
