### ISSUE TITLE
Implementation without storyboard

### ISSUE THREAD

**Issue by deviggner** [DenHeadless/ZoomInteractiveTransition#18]
Hello @DenHeadless 

I am trying to implement your library. I dont use storyboards. I have implemented like your sample project (set delegates, images, etc). But its not working.

What i need to do before run my pushviewcontroller? Or any other methods?

**Comment by DenHeadless** [comment]
Hey)

This project does not rely on storyboards at all, they are only used in example code for simplicity. The principle is really simple as well, i suggest digging into code, and looking on some examples on how interactive transition are implemented on iOS. There's no super special approach in this library, it's just an attempt to simplify one of transitions to really small amount of code.

**Comment by deviggner** [comment]
Hi @DenHeadless 
Thank you for quick reply. I've solved the problem. I was using a custom navigation controller with just an interactive pop gesture feature. When i changed my navigation controller to UINavigationController it worked. 

Thank you.
