### ISSUE TITLE
Disable Zoom-out transition

### ISSUE THREAD

**Issue by deviggner** [DenHeadless/ZoomInteractiveTransition#19]
Hello @DenHeadless 

I have another problem. I would like to disable the zoom out transition. So i only want it when push a view controller. Popping the view controller should be the native (left to right transition). How can i achieve this?

Thank you.

**Comment by DenTelezhkin** [comment]
We had delegate for this, i think, something like this

```
shouldAllowZoomTransitionForOperation:fromViewController:toViewController:
```

So you can become a delegate and decide whether you want animation or not.

**Comment by deviggner** [comment]
Great, it worked. Thank you so much @DenHeadless
