### ISSUE TITLE
major memory leak.

### ISSUE THREAD

**Issue by sdgbraincraft** [DenHeadless/ZoomInteractiveTransition#20]
Using XS Max. Showing images and videos with uipageviewcontroller. with 30 + images/videos, memory jumps up to 400 mb and never releases after pop.

**Comment by DenTelezhkin** [comment]
Hi!

Unfortunately, at this time I am unable to provide support for this framework. 

If you have a pull request that fixes problem you are describing, I can merge it and make a new release if you need that.
